[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-gnu-gcc"

[target.i686-unknown-linux-musl]
linker = "x86_64-linux-gnu-gcc"
