use std::collections::HashMap;
use std::hash::Hash;
use std::marker::PhantomData;

use itertools::Itertools;
use rayon::iter::{IntoParallelIterator, ParallelIterator};
use serde::*;

use crate::files::{FileHash, FileLen};

/// Groups items by key.
/// After all items have been added, this structure can be transformed into
/// an iterator over groups.
/// The order of groups in the output iterator is not defined.
/// The order of items in each group matches the order of adding the items by a thread.
///
/// Internally uses a hash map.
/// The amortized complexity of adding an item is O(1).
/// The complexity of reading all groups is O(N).
///
/// # Example
/// ```
/// use fclones::group::GroupMap;
/// let mut map = GroupMap::new(|item: (u32, u32)| (item.0, item.1));
/// map.add((1, 10));
/// map.add((2, 20));
/// map.add((1, 11));
/// map.add((2, 21));
///
/// let mut groups: Vec<_> = map.into_iter().collect();
///
/// groups.sort_by_key(|item| item.0);
/// assert_eq!(groups[0], (1, vec![10, 11]));
/// assert_eq!(groups[1], (2, vec![20, 21]));
/// ```
///
pub struct GroupMap<T, K, V, F>
    where K: PartialEq + Hash,
          F: Fn(T) -> (K, V)
{
    item_type: PhantomData<T>,
    groups: HashMap<K, Vec<V>>,
    split_fn: F,
}

impl<T, K, V, F> GroupMap<T, K, V, F>
    where K: Eq + Hash,
          F: Fn(T) -> (K, V),
{
    /// Creates a new empty map.
    ///
    /// # Arguments
    /// * `split_fn` - a function generating the key-value pair for each input item
    pub fn new(split_fn: F) -> GroupMap<T, K, V, F> {
        GroupMap { item_type: PhantomData, groups: HashMap::new(), split_fn }
    }

    /// Adds an item to the map.
    /// Note, this doesn't take `&mut self` so this can be called from safely from many threads.
    pub fn add(&mut self, item: T) {
        let (key, new_item) = (self.split_fn)(item);
        self.groups
            .entry(key)
            .or_insert(vec![])
            .push(new_item);
    }

    /// Returns number of groups larger than given min_size
    pub fn group_count(&self, min_size: usize) -> usize {
        self.groups.iter().filter(|g| g.1.len() >= min_size).count()
    }
}

impl<T, K, V, F> IntoIterator for GroupMap<T, K, V, F>
    where K: Eq + Hash,
          F: Fn(T) -> (K, V),
{
    type Item = (K, Vec<V>);
    type IntoIter = <HashMap<K, Vec<V>> as IntoIterator>::IntoIter;

    fn into_iter(self) -> Self::IntoIter {
        self.groups.into_iter()
    }
}


/// Represents a group of files that have something in common, e.g. same size or same hash
#[derive(Serialize, Debug)]
pub struct FileGroup<F> {
    pub len: FileLen,
    pub hash: Option<FileHash>,
    pub files: Vec<F>
}

/// Computes metrics for reporting summaries of each processing stage.
pub trait GroupedFileSetMetrics {

    /// Returns the total count of the files
    fn total_count(self) -> usize;

    /// Returns the sum of file lengths
    fn total_size(self) -> FileLen;

    /// Returns the total count of redundant files
    /// # Arguments
    /// * `max_rf` - maximum number of replicas allowed (they won't be counted as redundant)
    fn selected_count(self, rf_over: usize, rf_under: usize) -> usize;

    /// Returns the amount of data in redundant files
    /// # Arguments
    /// * `max_rf` - maximum number of replicas allowed (they won't be counted as redundant)
    fn selected_size(self, rf_over: usize, rf_under: usize) -> FileLen;
}


impl<'a, I, F> GroupedFileSetMetrics for I
    where I: IntoIterator<Item=&'a FileGroup<F>> + 'a,
          F: 'a
{
    fn total_count(self) -> usize {
        self.into_iter().map(|g| g.files.len()).sum()
    }

    fn total_size(self) -> FileLen {
        self.into_iter().map(|g| g.len * g.files.len() as u64).sum()
    }

    fn selected_count(self, rf_over: usize, rf_under: usize) -> usize {
        self.into_iter()
            .filter(|&g| g.files.len() < rf_under)
            .map(|g| g.files.len().saturating_sub(rf_over))
            .sum()
    }

    fn selected_size(self, rf_over: usize, rf_under: usize) -> FileLen {
        self.into_iter()
            .filter(|&g| g.files.len() < rf_under)
            .map(|g| g.len * g.files.len().saturating_sub(rf_over) as u64)
            .sum()
    }
}

pub trait SplitGroups<G, H> {

    /// Splits a collection of file groups into a collection of smaller
    /// file groups according to file hashes generated by `hash` function.
    /// The items for which the grouping function returns `None` are not further processed.
    ///
    /// This method does not merge groups together. If items in two different input groups
    /// generate the same key, they will remain in separate groups in the output.
    ///
    /// The operation is performed in parallel, so all arguments must be thread-safe.
    /// The order of items in the output is unspecified and must not be relied upon.
    ///
    /// # Example
    /// ```
    /// use rayon::iter::ParallelIterator;
    /// use fclones::files::{FileLen, FileHash};
    /// use fasthash::spooky::Hasher128;
    /// use fasthash::{FastHasher, HasherExt};
    /// use std::hash::Hasher;
    /// use fclones::group::{FileGroup, SplitGroups};
    /// use fclones::path::Path;
    ///
    /// let g = FileGroup { len: FileLen(10), hash: None, files: vec![
    ///     Path::from("file1"),
    ///     Path::from("file2")
    /// ]};
    ///
    /// fn hash(len: FileLen, hash: Option<FileHash>, path: &Path) -> Option<FileHash> {
    ///     let mut hasher = Hasher128::new();
    ///     hasher.write(path.to_string().as_bytes());
    ///     Some(FileHash(hasher.finish_ext()))
    /// }
    ///
    /// let mut groups = vec![g].split(1, hash);
    /// groups.sort_by_key(|g| g.files[0].clone());
    /// assert_eq!(groups[0].len, FileLen(10));
    /// assert_eq!(groups[0].files, vec![Path::from("file1")]);
    /// assert_eq!(groups[1].len, FileLen(10));
    /// assert_eq!(groups[1].files, vec![Path::from("file2")]);
    /// ```
    fn split(self, min_group_size: usize, hash: H) -> Vec<G>;
}

impl<H, F> SplitGroups<FileGroup<F>, H> for Vec<FileGroup<F>>
    where H: Fn(FileLen, Option<FileHash>, &F) -> Option<FileHash> + Sync + Send,
          F: Send
{
    fn split(self, min_group_size: usize, hash: H) -> Vec<FileGroup<F>> {
        self.into_par_iter()
            .flat_map(|g: FileGroup<F>| {
                if g.files.len() <= 1 {
                    vec![g]
                } else {
                    split_single(g, &hash)
                }
            })
            .filter(|g| g.files.len() >= min_group_size)
            .collect()
    }
}

fn split_single<H, F>(g: FileGroup<F>, hash: &H) -> Vec<FileGroup<F>>
    where H: Fn(FileLen, Option<FileHash>, &F) -> Option<FileHash> + Sync + Send,
          F: Send
{
    let file_len = g.len;
    let file_hash = g.hash;
    let mut hashed = g.files
        .into_par_iter()
        .filter_map(|f: F| (hash)(file_len, file_hash, &f).map(|h: FileHash| (h, f)))
        .collect::<Vec<_>>();

    hashed.sort_by_key(|(h, _p)| h.0);
    hashed
        .into_iter()
        .group_by(|(h, _)| *h)
        .into_iter()
        .map(|(hash, group)| FileGroup {
            len: file_len,
            hash: Some(hash),
            files: group.map(|(_hash, path)| path).collect()
        })
        .collect()
}
